### ISSUE TITLE
Failed  to run tests 

### ISSUE THREAD

**Issue by bertilpaiva** [jzheaux/terracotta-bank#2]
[RemoteTestNG] detected TestNG version 6.9.10
org.testng.TestNGException: 
Cannot instantiate class com.joshcummings.codeplay.terracotta.MakeDepositFunctionalTest
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:40)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:377)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:290)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:130)
	at org.testng.TestRunner.initMethods(TestRunner.java:424)
	at org.testng.TestRunner.init(TestRunner.java:247)
	at org.testng.TestRunner.init(TestRunner.java:217)
	at org.testng.TestRunner.<init>(TestRunner.java:169)
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:29)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:65)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:594)
	at org.testng.SuiteRunner.init(SuiteRunner.java:168)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1319)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1306)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1160)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	... 21 more
Caused by: java.lang.NullPointerException: uri was not specified
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.withDockerHost(DefaultDockerClientConfig.java:348)
	at com.joshcummings.codeplay.terracotta.testng.DockerSupport.<init>(DockerSupport.java:14)
	at com.joshcummings.codeplay.terracotta.AbstractEmbeddedTomcatSeleniumTest.<init>(AbstractEmbeddedTomcatSeleniumTest.java:32)
	at com.joshcummings.codeplay.terracotta.MakeDepositFunctionalTest.<init>(MakeDepositFunctionalTest.java:30)
	... 26 more

**Comment by bertilpaiva** [comment]
Docker is not properly set . What is the value for DOCKER_CERT_PATH ?
